version: '3.8'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mdpmdp
      USE_POSTGRES: 1
  flaskapp:
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
